
public extern static const uint TRANSMITTANCE_TEXTURE_WIDTH ;
public extern static const uint TRANSMITTANCE_TEXTURE_HEIGHT;

public extern static const uint SCATTERING_TEXTURE_R_SIZE  ;
public extern static const uint SCATTERING_TEXTURE_MU_SIZE ;
public extern static const uint SCATTERING_TEXTURE_MU_S_SIZE;
public extern static const uint SCATTERING_TEXTURE_NU_SIZE ;

public extern static const uint IRRADIANCE_TEXTURE_WIDTH;
public extern static const uint IRRADIANCE_TEXTURE_HEIGHT;